### ISSUE TITLE
Possible BlobHeader detection issue or data error at geofabrik

### ISSUE THREAD

**Issue by bjornharrtell** [b-r-u/osmpbf#38]
On todays download of https://download.geofabrik.de/europe-latest.osm.pbf I got this:

Error: Error(Blob(HeaderTooBig { size: 1008813135 }))

Possibly a data error at geofabrik because I read in spec that "The length of the BlobHeader should be less than 32 [KiB](http://en.wikipedia.org/wiki/Kibibyte) (32*1024 bytes) and must be less than 64 KiB".

But I cannot rule out that osmpbf is trying to decode something else as a BlobHeader?

**Comment by bjornharrtell** [comment]
My failure, I didn't follow links.

**Comment by jtarchie** [comment]
@bjornharrtell, I am getting this error, too. Can you clarify your last comment? I am unfamiliar with what links you are referring to.

**Comment by bjornharrtell** [comment]
Sorry I don't remember. 🙂
