### ISSUE TITLE
Distance between two points

### ISSUE THREAD

**Issue by andrewgy8** [b-r-u/osmpbf#6]
Hey! Not sure this is the right place for this, but Ill ask anyway. Im trying to get the distance between two sets of lat/lon on a map. Would this be the right lib to get this done? Is it in the scope of this project?
Thanks!

**Comment by b-r-u** [comment]
Hi! I think that distance calculations are not in scope for this library because there are just so many ways to do it. But you could combine this library with your own implementation of the haversine formula :)

**Comment by andrewgy8** [comment]
Thanks! Thats what I was afraid of. Ill continue digging into how to find driving distance between two points. But first Ill start small with haversine. I appreciate the help. Cheers!

**Comment by b-r-u** [comment]
If you want to calculate the driving distance, you could build a graph of streets using [this function](https://docs.rs/osmpbf/0.2.0/osmpbf/indexed/struct.IndexedReader.html#method.read_ways_and_deps) by filtering ways with the `highway` tag.
